import { useRouter } from 'next/router'
import  Link from 'next/link'
import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  const router = useRouter()

  useEffect(() => {
    const token = localStorage.getItem('token')
    if (!token) router.push('/login')
  }, [])

  const logoutHandler = () => {
    localStorage.removeItem('token')
    router.push('/login')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Main Repo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">MainRepo</a>
        </h1>

        <p className={styles.description}>
          <button className={styles.button} onClick={logoutHandler}>Logout</button>
        </p>

        <div className={styles.grid}>
          <Link href="/menu1">
            <a className={styles.card}>
              <h2>Menu 1 &rarr;</h2>
              <p>Built inside this repository. This (main) repository use to have main responbility</p>
            </a>
          </Link>

          <Link href="/menu2">
            <a className={styles.card}>
              <h2>Menu 2 &rarr;</h2>
              <p>Built outside this repository. The repository connected using git subtree</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
